name: FREEZONE - ZONE LIBRE
favicon: null
layout_spectrum: 0.7884005894884467
typography_spectrum: 0.9088589574676007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6741104836110026
  lightness: 0.3232132620178163
  saturation: 0.6918734030332416
  rhythmicContrast: 0.3970887325704098
purpose: []
